### ISSUE TITLE
Token System

### ISSUE THREAD

**Issue by cosban** [cosban/gohst#26]
There are multiple kinds of tokens.

## Spendable tokens
   * Earn these each day that you log in
   * Earn additional tokens each day that reputation is changed
   * Earn more for each consecutive day this occurs (in a logarithmic fashion)
   * Able to be spent on things within the shop

## Bounty Tokens
   * Only able to be given out by owners
   * Good for asking users to do tasks

## Karma tokens
   * Both positive and negative
   * Only able to be used once (can't be taken away)
   * Must be purchased

**Comment by Thyplozix** [comment]
Are we earning points to spend in the shop by way of posting or?

**Comment by cosban** [comment]
You earn an amount of spendable tokens each day you log in.
You earn additional tokens if you add to your rep.

**Comment by Thyplozix** [comment]
Does this account for persistent login?

**Comment by cosban** [comment]
Yes. It means you have to actually visit the site to earn the tokens.
